import { it, expect, vi } from 'vitest';
import { PitchWorkerClient, type PitchJob } from './pitchWorkerClient';
it('bounds work to one running and latest pending frame, preserving capture time', () => {
  const worker = { onmessage: null as null | ((e: unknown) => void), onerror: null, postMessage: vi.fn(), terminate: vi.fn() };
  const callback = vi.fn();
  const client = new PitchWorkerClient(worker as unknown as Worker, callback);
  const frame = (timeSec: number): PitchJob => ({ samples: new Float32Array(4096), sampleRate: 48000, timeSec });
  for (let i = 0; i < 100; i++) client.submit(frame(i));
  expect(worker.postMessage).toHaveBeenCalledTimes(1);
  worker.onmessage!({ data: { pitch: null, timeSec: 0 } });
  expect(callback).toHaveBeenCalledWith(null, 0);
  expect(worker.postMessage).toHaveBeenCalledTimes(2);
  expect(worker.postMessage.mock.calls[1][0].timeSec).toBe(99);
  const stale = worker.onmessage!;
  client.stop();
  stale({ data: { pitch: null, timeSec: 99 } });
  client.submit(frame(100));
  expect(callback).toHaveBeenCalledTimes(1);
  expect(worker.terminate).toHaveBeenCalledTimes(1);
  expect(worker.postMessage).toHaveBeenCalledTimes(2);
});
