/**
 * Offline bench for the pattern-variation work: runs each genre's pattern bank over 32 bars
 * at creativity 0 / 0.5 / 1 and reports, per instrument, how many distinct bar "signatures"
 * appear, the mean events per bar, and how many fills fired. A reviewer can use this to
 * confirm creativity actually buys variety instead of chaos or silence.
 *
 * Run with: npm run bench:patterns
 */
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { mulberry32 } from '../../src/rng';
import { GENRES, INSTRUMENTS } from '../../src/types';
import type { BarContext, Dynamics, Genre, Instrument } from '../../src/types';
import { PATTERNS } from '../../src/patterns/index';
import { DRUM } from '../../src/types';

const __dirname = dirname(fileURLToPath(import.meta.url));
const KEY = { root: 7, mode: 'major' as const };
const BARS = 32;
const CREATIVITIES = [0, 0.5, 1];
const DYN: Dynamics = { intensity: 0.6, space: true, fillDue: false, silenceBeats: 1 };

interface Row { genre: Genre; instrument: Instrument; creativity: number; signatures: number; meanEvents: string; fills: number }

function fmt(n: number): string { return n.toFixed(2); }

function main() {
  const rows: Row[] = [];
  for (const genre of GENRES) {
    const bank = PATTERNS[genre];
    for (const creativity of CREATIVITIES) {
      for (const inst of INSTRUMENTS) {
        const sigs = new Set<string>();
        let totalEvents = 0, fills = 0;
        for (let bar = 0; bar < BARS; bar++) {
          const ctx: BarContext = {
            bar, key: KEY, creativity, dynamics: DYN,
            rng: mulberry32(bar * 7919 + Math.round(creativity * 1000) + 17),
          };
          const events = bank[inst].nextBar(ctx);
          sigs.add(JSON.stringify(events.map(e => [Math.round(e.time * 100), e.note, Math.round(e.velocity * 100)])));
          totalEvents += events.length;
          if (inst === 'drums') fills += events.filter(e => e.note === DRUM.crash || (e.note === DRUM.snare && e.velocity < 0.65 && e.time > 3)).length;
        }
        rows.push({ genre, instrument: inst, creativity, signatures: sigs.size, meanEvents: fmt(totalEvents / BARS), fills });
      }
    }
  }

  const header = `| genre | instrument | creativity | distinct bar signatures / ${BARS} | mean events/bar | fill-ish hits |`;
  const sep = '|---|---|---|---|---|---|';
  const lines = rows.map(r => `| ${r.genre} | ${r.instrument} | ${r.creativity} | ${r.signatures} | ${r.meanEvents} | ${r.fills} |`);
  const table = [header, sep, ...lines].join('\n');

  console.log(table);

  const md = `# Pattern variation bench\n\nGenerated by \`npm run bench:patterns\`. ${BARS} bars per cell, dynamics fixed at intensity ${DYN.intensity}, space ${DYN.space}.\n\n${table}\n`;
  writeFileSync(join(__dirname, 'RESULTS.md'), md);
}

main();
